### ISSUE TITLE
Group Projects - Milestone 2

### ISSUE THREAD

**Issue by bChakrabarty** [data301-2020-winter1/course-project-group_6007b#8]
## High priority (must-fix)
- [x] Add description in all the graphs, especially define your motive and outcome
- [x] Make sure everyone can watch these images, 
course-project-group_6007b/blob/main/analysis/submitted/submit.ipynb

## Medium Priority (should-fix)
- [x] Explore the change in the genre of videos people are watching 
- [x] Explore which attributes (e.g., description, tags, title) increases views

## Low priority (fix if there is time)
- [x] Is video upload timing important? Can a channel get an advantage over others just by publishing the video at a particular time?
